<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.liferay</groupId>
  <artifactId>com.liferay.object.web</artifactId>
  <version>1.0.110</version>
  <packaging>pom</packaging>
  <dependencies>
    <dependency>
      <groupId>javax.portlet</groupId>
      <artifactId>portlet-api</artifactId>
      <version>3.0.1</version>
    </dependency>
    <dependency>
      <groupId>javax.servlet.jsp</groupId>
      <artifactId>javax.servlet.jsp-api</artifactId>
      <version>2.3.1</version>
    </dependency>
    <dependency>
      <groupId>javax.ws.rs</groupId>
      <artifactId>javax.ws.rs-api</artifactId>
      <version>2.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.felix</groupId>
      <artifactId>org.apache.felix.http.servlet-api</artifactId>
      <version>1.1.2</version>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.component.annotations</artifactId>
      <version>1.4.0</version>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>osgi.core</artifactId>
      <version>6.0.0</version>
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <id>apache</id>
      <name>Apache</name>
      <url>https://repo.maven.apache.org/maven2</url>
      <layout>default</layout>
    </repository>
    <repository>
      <id>liferay-public</id>
      <name>Liferay Public</name>
      <url>https://repository.liferay.com/nexus/content/repositories/public</url>
      <layout>default</layout>
    </repository>
    <repository>
      <id>jaspersoft-third-party</id>
      <name>Jaspersoft Third-Party</name>
      <url>http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts</url>
      <layout>default</layout>
    </repository>
  </repositories>
</project>