buildscript {
	dependencies {
		classpath files("/home/mateus/Liferay/liferay-portal/modules/sdk/gradle-plugins-workspace/build/tmp/jar/com.liferay.gradle.plugins.workspace-7.0.2.jar")
		classpath files("/home/mateus/Liferay/liferay-portal/modules/sdk/gradle-plugins-workspace/lib/com.liferay.workspace.bundle.url.codec-1.0.0.jar")
		classpath group: "biz.aQute.bnd", name: "biz.aQute.bnd.gradle", version: "5.2.0"
		classpath group: "com.bmuschko", name: "gradle-docker-plugin", version: "6.7.0"
		classpath group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.10.3"
		classpath group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-yaml", version: "2.10.3"
		classpath group: "com.github.docker-java", name: "docker-java", version: "3.2.8"
		classpath group: "com.google.code.gson", name: "gson", version: "2.9.0"
		classpath group: "com.liferay", name: "com.liferay.ant.bnd", version: "3.2.9"
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins", version: "14.0.157"
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.poshi.runner", version: "3.0.73"
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.target.platform", version: "3.0.12"
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.theme.builder", version: "2.0.23"
		classpath group: "com.liferay", name: "com.liferay.petra.lang", version: "5.1.2"
		classpath group: "com.liferay", name: "com.liferay.petra.string", version: "5.2.0"
		classpath group: "com.liferay", name: "com.liferay.portal.tools.bundle.support", version: "3.7.3"
		classpath group: "com.liferay", name: "com.liferay.portal.tools.soy.builder", version: "3.0.4"
		classpath group: "de.undercouch", name: "gradle-download-task", version: "5.0.0"
		classpath group: "net.java.dev.jna", name: "jna", version: "5.8.0"
		classpath group: "net.saliman", name: "gradle-properties-plugin", version: "1.4.6"
	}

	repositories {
		mavenLocal()

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}

		maven {
			url new File(rootProject.projectDir, "../../.m2-tmp")
		}
	}
}

apply plugin: "com.liferay.workspace"

include "poshi"