name: Count Pull Request

# on:
#   workflow_dispatch:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '40 19 * * *'

on:
  workflow_dispatch: {}
  push:
    branches:
      - pullRequestAction

# on:
#   push:
#     branches:
#       - pullRequestAction # Specify the branch where the workflow should run

jobs:
  pr_stats:
    runs-on: ubuntu-latest

    steps:

    - name: Limpar cache das dependências
      run: npm cache clean --force
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run script to fetch PR statistics
      run: |
       node github/fetch_pr_stats.js ${{ secrets.GITHUB_TOKEN }}

